name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  
env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Initialize and update all submodules
        run: |
          git submodule update --init --recursive
          cd lib/devtools && git submodule update --init --recursive || true
          cd ../layerzero-v2 && git submodule update --init --recursive || true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version
          
      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build with warnings as errors
        run: |
          forge build --sizes --optimize --optimizer-runs 200 --deny-warnings
        id: build

      - name: Run Forge tests with warnings as errors
        run: |
          forge test -vvv --deny-warnings
        id: test
