name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  
env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'    # pin a version instead of using .nvmrc
          cache: 'pnpm'

      - name: Install DevTools dependencies
        working-directory: lib/devtools
        run: pnpm install --frozen-lockfile

      - name: Build DevTools packages
        working-directory: lib/devtools
        run: pnpm build

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version
          
      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build with warnings as errors
        run: |
          forge build --sizes --optimize --optimizer-runs 200 --deny-warnings
        id: build

      - name: Run Forge tests with warnings as errors
        run: |
          forge test -vvv --deny-warnings
        id: test
